// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7rEOoUS0hi1IhU_qEKj97iecgIhYnoYw',
    appId: '1:147379063492:web:2fb81aa243a9bd96f85791',
    messagingSenderId: '147379063492',
    projectId: 'aamchibites',
    authDomain: 'aamchibites.firebaseapp.com',
    databaseURL: 'https://aamchibites-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aamchibites.firebasestorage.app',
    measurementId: 'G-H64253YNPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBTCVcZN3a_biAC2FYYgAkXdS1fmXBw7o',
    appId: '1:147379063492:android:a9c4eac13910b70ef85791',
    messagingSenderId: '147379063492',
    projectId: 'aamchibites',
    databaseURL: 'https://aamchibites-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aamchibites.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApIWjqtfyB2EBRjdEwUjdAAPZSuscjoXc',
    appId: '1:147379063492:ios:0821ae13877879cff85791',
    messagingSenderId: '147379063492',
    projectId: 'aamchibites',
    databaseURL: 'https://aamchibites-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aamchibites.firebasestorage.app',
    iosBundleId: 'com.example.streetFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApIWjqtfyB2EBRjdEwUjdAAPZSuscjoXc',
    appId: '1:147379063492:ios:0821ae13877879cff85791',
    messagingSenderId: '147379063492',
    projectId: 'aamchibites',
    databaseURL: 'https://aamchibites-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aamchibites.firebasestorage.app',
    iosBundleId: 'com.example.streetFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7rEOoUS0hi1IhU_qEKj97iecgIhYnoYw',
    appId: '1:147379063492:web:28f1175305cd6b07f85791',
    messagingSenderId: '147379063492',
    projectId: 'aamchibites',
    authDomain: 'aamchibites.firebaseapp.com',
    databaseURL: 'https://aamchibites-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aamchibites.firebasestorage.app',
    measurementId: 'G-30ZYH34D3S',
  );
}
